# Generated by Django 5.2.8 on 2025-11-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
