# Generated by Django 5.2.3 on 2025-12-15 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
        ('core', '0002_delete_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Detail',
                'verbose_name_plural': 'Details',
                'db_table': 'detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('abonnement_utilisateur_id', models.BigIntegerField(blank=True, db_column='abonnement_utilisateur_id', null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(blank=True, max_length=3, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('client_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.CharField(blank=True, max_length=255, null=True)),
                ('client_adresse', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('date_emission', models.DateTimeField(blank=True, null=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_echeance', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='compte.compte')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'facture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('devise', models.CharField(blank=True, max_length=3, null=True)),
                ('duree_jours', models.IntegerField()),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actif', models.BooleanField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
                ('details', models.ManyToManyField(db_table='plan_abonnement_detail', related_name='plans', to='core.detail')),
            ],
            options={
                'verbose_name': 'Plan Abonnement',
                'verbose_name_plural': 'Plans Abonnement',
                'db_table': 'plan_abonnement',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Abonnement',
        ),
    ]
