# Generated by Django 5.2.3 on 2025-12-15 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_detail_facture_planabonnement_delete_abonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnementDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('detail', models.ForeignKey(db_column='detail_id', on_delete=django.db.models.deletion.CASCADE, to='core.detail')),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='core.planabonnement')),
            ],
            options={
                'db_table': 'plan_abonnement_detail',
                'managed': True,
                'unique_together': {('plan', 'detail')},
            },
        ),
        migrations.AlterField(
            model_name='planabonnement',
            name='details',
            field=models.ManyToManyField(related_name='plans', through='core.PlanAbonnementDetail', to='core.detail'),
        ),
    ]
