# Generated by Django 5.2.8 on 2026-03-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_planabonnementdetail_alter_planabonnement_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('event_type', models.CharField(choices=[('registration_step', 'Étape inscription'), ('registration_complete', 'Inscription terminée'), ('registration_abandon', 'Abandon inscription'), ('page_view', 'Vue de page')], db_index=True, max_length=50)),
                ('step', models.IntegerField(blank=True, db_index=True, null=True)),
                ('step_name', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('compte_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'tracking_user_event',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='detail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planabonnement',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='planabonnementdetail',
            options={'managed': False},
        ),
    ]
