# Generated by Django 5.2.8 on 2026-03-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userevent_alter_detail_options_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('referrer', models.CharField(blank=True, default='', max_length=1000)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('device_type', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'tracking_page_view',
                'managed': True,
                'indexes': [models.Index(fields=['path', 'created_at'], name='tracking_pa_path_a3a28b_idx'), models.Index(fields=['ip_address', 'created_at'], name='tracking_pa_ip_addr_03429b_idx')],
            },
        ),
    ]
