# Generated by Django 5.2.8 on 2026-03-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pageview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pageview',
            name='username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
