---
all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/ansible_key
    ansible_python_interpreter: /usr/bin/python3

  children:
    monitoring_server:
      hosts:
        ServeurCentral:
          ansible_host: 173.249.47.92

    monitored_servers:
      hosts:
        FRONTEND:
          ansible_host: 86.48.5.225

