# Generated by Django 5.2.8 on 2026-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PgArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('sous_titre', models.CharField(blank=True, max_length=500, null=True)),
                ('petit_description', models.TextField(blank=True, null=True)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=500, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(blank=True, null=True)),
                ('reading_time', models.IntegerField(blank=True, null=True)),
                ('mis_en_avant', models.BooleanField(blank=True, null=True)),
                ('auteur_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('canonical_url', models.CharField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('schema_markup', models.JSONField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=95, null=True)),
                ('og_description', models.CharField(blank=True, max_length=160, null=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_for_seo', models.DateTimeField(blank=True, null=True)),
                ('faq_suggestions', models.JSONField(blank=True, null=True)),
                ('photo_description', models.TextField(blank=True, null=True)),
                ('photo_highlight', models.CharField(blank=True, max_length=500, null=True)),
                ('vignette', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_video_title', models.CharField(blank=True, max_length=500, null=True)),
                ('trending_keywords', models.JSONField(blank=True, null=True)),
                ('related_questions', models.JSONField(blank=True, null=True)),
                ('youtube_video_url', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_video_embed', models.CharField(blank=True, max_length=500, null=True)),
                ('youtube_video_thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('photos', models.JSONField(blank=True, null=True)),
                ('tags_list', models.JSONField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articles',
                'managed': False,
            },
        ),
    ]
