# Generated by Django 5.2.3 on 2025-12-15 04:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttranceGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'compte_attrancegenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caractere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('caractere', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_caractere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('numberPhone', models.CharField(max_length=20, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, max_length=50, null=True)),
                ('date_de_naissance', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('taille', models.CharField(blank=True, max_length=50, null=True)),
                ('poids', models.CharField(blank=True, max_length=50, null=True)),
                ('yeux', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('situation', models.CharField(blank=True, max_length=50, null=True)),
                ('enfant', models.CharField(blank=True, default='false', max_length=50, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(blank=True, max_length=50, null=True)),
                ('metier', models.CharField(blank=True, max_length=100, null=True)),
                ('recherche', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnique', models.CharField(blank=True, max_length=50, null=True)),
                ('shilhouette', models.CharField(blank=True, max_length=50, null=True)),
                ('glasses', models.CharField(blank=True, default='false', max_length=50, null=True)),
                ('sport', models.CharField(blank=True, default='false', max_length=50, null=True)),
                ('tatouage_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('handicap', models.CharField(blank=True, default='false', max_length=50, null=True)),
                ('hair_style', models.CharField(blank=True, max_length=50, null=True)),
                ('facial_hair', models.CharField(blank=True, max_length=50, null=True)),
                ('pays', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('ouverture', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('en_couple', models.BooleanField(blank=True, default=False)),
                ('credit', models.IntegerField(blank=True, default=0, null=True)),
                ('chartre', models.BooleanField(blank=True, default=False)),
                ('cgu', models.BooleanField(blank=True, default=False)),
                ('cookie', models.BooleanField(blank=True, default=False)),
                ('is_member', models.BooleanField(blank=True, default=False)),
                ('is_staff', models.BooleanField(blank=True, default=False)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('is_online', models.BooleanField(blank=True, default=False)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('smoke', models.CharField(blank=True, max_length=50, null=True)),
                ('alcool', models.CharField(blank=True, max_length=50, null=True)),
                ('animaux', models.CharField(blank=True, max_length=50, null=True)),
                ('disponible', models.CharField(blank=True, max_length=50, null=True)),
                ('abonnement', models.CharField(blank=True, default='gratuit', max_length=30, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'db_table': 'compte_compte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteAttranceGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'compte_compte_attirance_genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteBlacklist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compte_blacklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteCaractere',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_caractere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteCompteAttranceGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_attrancegenre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteFilm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_style_de_film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteHobie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_hobie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteLangue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_langue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compte_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compte_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteMusique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_style_de_musique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComptePiercing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_piercings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComptePreferenceEthnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_preference_ethnique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteSortie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('preference', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'compte_compte_preference_de_sortie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteTendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_tendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteVue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compte_vue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteZonesConfort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'compte_compte_zones_confort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteZonesconfortLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'compte_compte_zonesconfort',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('film', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_film',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hobie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hobie', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_hobie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('langue', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_langue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('musique', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_musique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photos', models.TextField(default='')),
                ('type_photo', models.CharField(default='', max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('est_active', models.BooleanField(default=True)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('is_nsfw_checked', models.BooleanField(default=False)),
                ('is_shocking', models.BooleanField(default=False)),
                ('is_shocking_checked', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compte_photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compte_photo_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoLike',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compte_photo_like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Piercing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('piercing', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_piercing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenceEthnique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_preferenceethnique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_moderation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compte_profilecomment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sortie', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_sortie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tendance', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_tendance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonesConfort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'compte_zonesconfort',
                'managed': False,
            },
        ),
    ]
