# Generated by Django 5.2.3 on 2025-12-15 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attrancegenre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='caractere',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': True, 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AlterModelOptions(
            name='compteattrancegenre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='compteblacklist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptecaractere',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptecompteattrancegenre',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptefilm',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptehobie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptelangue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptelike',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptematch',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptemusique',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptepiercing',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptepreferenceethnique',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptesortie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptetendance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptevue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptezonesconfort',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='comptezonesconfortlink',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hobie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='langue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='musique',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='photocomment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='photolike',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piercing',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='preferenceethnique',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='profilecomment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sortie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tendance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='zonesconfort',
            options={'managed': True},
        ),
    ]
