# Generated by Django 5.2.3 on 2026-01-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_alter_attrancegenre_options_alter_caractere_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
