# Generated by Django 5.2.3 on 2026-01-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_add_thumbnail_to_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteLike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(db_column='compte_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='compte.compte')),
                ('like', models.ForeignKey(db_column='like_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='compte.compte')),
            ],
            options={
                'db_table': 'compte_like',
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='comptelike',
            unique_together={('compte', 'like')},
        ),
    ]
