# Generated by Django 5.2.8 on 2026-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_create_compte_like_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementUtilisateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('montant_paye', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('renouvellement_auto', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('mollie_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mollie_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mollie_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mollie_mandate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_provider', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'abonnement_utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteBoost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compte_boost',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteCouple',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compte_couple',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompteProfileVue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compte_profile_vue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SignalementUtilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'compte_signalement_utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=255, null=True)),
                ('titre', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('duree_secondes', models.IntegerField(blank=True, null=True)),
                ('est_active', models.BooleanField(default=True)),
                ('est_publique', models.BooleanField(default=True)),
                ('vues', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'compte_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('signale', models.BooleanField(blank=True, default=False, null=True)),
                ('raison_signalement', models.TextField(blank=True, null=True)),
                ('date_signalement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_moderation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compte_video_comment',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AttranceGenre',
        ),
        migrations.DeleteModel(
            name='CompteCompteAttranceGenre',
        ),
        migrations.DeleteModel(
            name='CompteMatch',
        ),
        migrations.DeleteModel(
            name='ComptePiercing',
        ),
        migrations.DeleteModel(
            name='CompteVue',
        ),
        migrations.DeleteModel(
            name='CompteZonesconfortLink',
        ),
        migrations.DeleteModel(
            name='Piercing',
        ),
        migrations.DeleteModel(
            name='Sortie',
        ),
        migrations.DeleteModel(
            name='ZonesConfort',
        ),
        migrations.AlterModelOptions(
            name='caractere',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compte',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compteattrancegenre',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compteblacklist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptecaractere',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptefilm',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptehobie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptelangue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptelike',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptemusique',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptepreferenceethnique',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptesortie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptetendance',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comptezonesconfort',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hobie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='langue',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='musique',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='photocomment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='photolike',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='preferenceethnique',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='profilecomment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tendance',
            options={'managed': False},
        ),
    ]
